language:
  node_js

node_js:
  10.3.0

before_install:
  - export CHROME_BIN=chromium-browser
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - npm install -g karma-cli
  - npm install

script:
  karma start --singleRun