dist: trusty

sudo: required

language:
  node_js

node_js:
  10.3.0

before_install:
  - export CHROME_BIN=/usr/bin/chromium-browser/chrome-sandbox
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - 'sudo chown root /usr/lib/chromium-browser/chrome-sandbox'
  - 'sudo chmod 4755 /usr/lib/chromium-browser/chrome-sandbox'

install:
  - npm install -g karma-cli
  - npm install

script:
  karma start --singleRun