sudo: required

language:
  node_js

node_js:
  10.3.0

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install -g karma-cli
  - npm install

script:
  karma start --singleRun